[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "xchainpy2_thorchain_amm"
version = "0.0.30"
authors = [
    { name = "Tirinox", email = "developer@tirinox.ru" },
]
description = "XChainPy2 THORChain Automated Market Maker (AMM) interface"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["Crypto", "THORChain", "Blockchain", "XChain", "AMM", "Swap", "DEX"]
license = { text = "MIT" }
urls = {source = "https://github.com/tirinox/xchainpy"}
classifiers = [
    'Development Status :: 3 - Alpha',
    # Chose either "3 - Alpha", "4 - Beta" or "5 - Production/Stable" as the current state of your package
    'Intended Audience :: Developers', # Define that your audience are developers
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]
dependencies = [
    "bip-utils>=2.7.0,<3.0.0",
    "pycryptodome>=3.17,<4.0",
    "xchainpy2_utils>=0.0.4",
    "xchainpy2_crypto>=0.0.4",
    "xchainpy2_client>=0.0.4",
    "xchainpy2_thorchain>=0.0.4",
    "xchainpy2_cosmos>=0.0.4",
    "xchainpy2_thorchain_query>=0.0.4",
    "xchainpy2_wallet>=0.0.1",
]
[project.optional-dependencies]
test = ["pytest"]
